name: Mirror repositories

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: pip3 install -r requirements.txt

            - name: Run updater
              run: python3 updater.py