name: Mirror repositories

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: pip3 install -r requirements.txt

            - name: Reset Git credentials
              run: git config --global --unset credential.helper

            - name: Run updater
              env:
                ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
                ORG_GITHUB_USER: ${{ secrets.ORG_GITHUB_USER }}
              run: python3 updater.py
